export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "demo@devstash.io",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_link", name: "Link", icon: "Link", color: "#10b981", isSystem: true },
  { id: "type_file", name: "File", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Image", icon: "Image", color: "#ec4899", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 10,
    dominantTypeId: "type_snippet",
  },
  {
    id: "col_2",
    name: "AI Prompts",
    description: "Collection of useful AI prompts and templates",
    isFavorite: true,
    itemCount: 4,
    dominantTypeId: "type_prompt",
  },
  {
    id: "col_3",
    name: "DevOps Commands",
    description: "Docker, Git, and CLI commands",
    isFavorite: true,
    itemCount: 15,
    dominantTypeId: "type_command",
  },
  {
    id: "col_4",
    name: "Documentation",
    description: "Links to useful documentation",
    isFavorite: false,
    itemCount: 20,
    dominantTypeId: "type_link",
  },
  {
    id: "col_5",
    name: "Meeting Notes",
    description: "Sprint planning and team meeting notes",
    isFavorite: false,
    itemCount: 7,
    dominantTypeId: "type_note",
  },
  {
    id: "col_6",
    name: "Interview Prep",
    description: "Snippets and notes for technical interviews",
    isFavorite: true,
    itemCount: 9,
    dominantTypeId: "type_snippet",
  },
  {
    id: "col_7",
    name: "Misc",
    description: "Random useful stuff",
    isFavorite: false,
    itemCount: 6,
    dominantTypeId: "type_snippet",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "React useEffect cleanup",
    description: "Proper cleanup pattern for async operations in useEffect",
    contentType: "TEXT",
    content: `useEffect(() => {\n  const controller = new AbortController();\n  // fetch with controller.signal\n  return () => controller.abort();\n}, []);`,
    language: "typescript",
    itemTypeId: "type_snippet",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "hooks"],
    collectionIds: ["col_1"],
  },
  {
    id: "item_2",
    title: "Git interactive rebase",
    description: "Squash or edit last 5 commits",
    contentType: "TEXT",
    content: `git rebase -i HEAD~5`,
    language: "bash",
    itemTypeId: "type_command",
    isFavorite: false,
    isPinned: true,
    tags: ["git", "rebase"],
    collectionIds: ["col_3"],
  },
  {
    id: "item_3",
    title: "Code review assistant",
    description: "GPT prompt for thorough code reviews",
    contentType: "TEXT",
    content: `You are a senior developer reviewing code. Analyze the following for:\n1. Potential bugs and edge cases\n2. Performance issues\n3. Security concerns`,
    language: null,
    itemTypeId: "type_prompt",
    isFavorite: false,
    isPinned: false,
    tags: ["gpt", "review"],
    collectionIds: ["col_2"],
  },
  {
    id: "item_4",
    title: "Docker compose up with rebuild",
    description: "Rebuild and start containers with live logs",
    contentType: "TEXT",
    content: `docker-compose up --build -d && docker-compose logs -f`,
    language: "bash",
    itemTypeId: "type_command",
    isFavorite: false,
    isPinned: false,
    tags: ["docker", "devops"],
    collectionIds: ["col_3"],
  },
  {
    id: "item_5",
    title: "API Design Principles",
    description: "Notes from API design workshops",
    contentType: "TEXT",
    content: `## RESTful API Best Practices\n\n- Use nouns for resources, verbs for actions.\n- Return consistent error shapes.`,
    language: null,
    itemTypeId: "type_note",
    isFavorite: false,
    isPinned: false,
    tags: ["api", "design"],
    collectionIds: ["col_4"],
  },
  {
    id: "item_6",
    title: "Tailwind CSS Docs",
    description: "Official Tailwind documentation",
    contentType: "URL",
    url: "https://tailwindcss.com/docs",
    language: null,
    itemTypeId: "type_link",
    isFavorite: true,
    isPinned: false,
    tags: ["css", "tailwind", "ui"],
    collectionIds: ["col_4"],
  },
  {
    id: "item_7",
    title: "TypeScript utility types",
    description: "Useful TypeScript utility types",
    contentType: "TEXT",
    content: `type DeepPartial<T> = {\n  [P in keyof T]?: T[P] extends object\n    ? DeepPartial<T[P]>\n    : T[P];\n};`,
    language: "typescript",
    itemTypeId: "type_snippet",
    isFavorite: false,
    isPinned: false,
    tags: ["typescript", "types"],
    collectionIds: ["col_1", "col_6"],
  },
  {
    id: "item_8",
    title: "System prompt template",
    description: "Template for creating effective system prompts",
    contentType: "TEXT",
    content: `You are {ROLE}. Your primary goal is {GOAL}.\n\n## Guidelines,\n- ...`,
    language: null,
    itemTypeId: "type_prompt",
    isFavorite: false,
    isPinned: false,
    tags: ["system-prompt", "ai-engineering"],
    collectionIds: ["col_2"],
  },
];

export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 8,
  type_command: 15,
  type_note: 12,
  type_link: 27,
  type_file: 6,
  type_image: 5,
};
